CC = gcc
FLAGS = -Wall -Wextra -Wfloat-equal -Wshadow -Wpointer-arith -Wcast-align -Wconversion
TARGET = ../../target

all: command.o

command.o: 
	$(CC) -c ./command.c -o $(TARGET)/command.o $(FLAGS)
